"use client";

import { FormEvent, useEffect, useState } from "react";
import { SiteHeader } from "@/components/SiteHeader";

type Slot={id:string; startsAt:string; capacity:number; remaining:number};
type Reservation={id:string; slotId:string; attendeeCount:number; status:"confirmed"|"cancelled"};
const api=process.env.NEXT_PUBLIC_RESERVATIONS_API;
const demoSlots:Slot[]=[
  {id:"demo-oct-7-1600",startsAt:"2026-10-07T16:00:00-07:00",capacity:12,remaining:12},
  {id:"demo-oct-7-1700",startsAt:"2026-10-07T17:00:00-07:00",capacity:12,remaining:12},
];
const formatSlot=(value:string)=>new Date(value).toLocaleString("en-US",{weekday:"long",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"});

export default function OfficeVisitPage(){
  const [slots,setSlots]=useState<Slot[]>(demoSlots); const [selected,setSelected]=useState(""); const [party,setParty]=useState<1|2>(1); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [guestName,setGuestName]=useState(""); const [reservation,setReservation]=useState<Reservation>(); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  useEffect(()=>{if(!api)return;fetch(`${api}/slots`).then(r=>r.ok?r.json() as Promise<{slots:Slot[]}>:Promise.reject()).then(data=>setSlots(data.slots)).catch(()=>setMessage("Live availability is unavailable. Demo slots are shown; no reservation has been made."))},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setMessage("");if(!selected||!name.trim()||!email.trim()||(party===2&&!guestName.trim()))return setMessage("Choose a slot and complete the required details.");if(!api)return setMessage("Demo mode only: set NEXT_PUBLIC_RESERVATIONS_API to the deployed Worker before accepting reservations.");setLoading(true);try{const response=await fetch(`${api}/reservations`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({slotId:selected,attendeeCount:party,memberName:name.trim(),memberEmail:email.trim(),guestName:party===2?guestName.trim():undefined})});const data=await response.json() as {reservation?:Reservation;error?:string};if(!response.ok)throw new Error(data.error||"Reservation could not be saved");setReservation(data.reservation);setMessage("Your visit is confirmed.")}catch(error){setMessage(error instanceof Error?error.message:"Reservation could not be saved.")}finally{setLoading(false)}};
  const cancel=async()=>{if(!reservation||!api)return;setLoading(true);try{const r=await fetch(`${api}/reservations/${reservation.id}`,{method:"DELETE"});if(!r.ok)throw new Error("Cancellation could not be completed");setReservation(undefined);setMessage("Reservation cancelled.")}catch(error){setMessage(error instanceof Error?error.message:"Cancellation could not be completed.")}finally{setLoading(false)}};
  return <main><SiteHeader/><section className="visit-head wrap"><p className="mono-label">PRODUCT.AI OFFICE / GOLDEN HOUR 008</p><h1>Reserve your office visit.</h1><p>Wednesday, October 7, 2026. Tech Week planning needs no sign-in; a visit reservation uses only the contact details needed to manage it.</p>{!api&&<p className="demo-banner">DEMO CONFIGURATION — Slots and capacity are placeholders. This screen does not create a production reservation.</p>}</section><section className="visit-grid wrap"><form className="visit-form" onSubmit={submit}><fieldset><legend>1 / Pick a time</legend>{slots.map(slot=><label className={`slot-option ${selected===slot.id?"selected":""}`} key={slot.id}><input type="radio" name="slot" value={slot.id} checked={selected===slot.id} onChange={()=>setSelected(slot.id)}/><span>{formatSlot(slot.startsAt)}</span><em>{slot.remaining} of {slot.capacity} spaces left</em></label>)}</fieldset><fieldset><legend>2 / Who’s visiting?</legend><div className="party-toggle"><button type="button" className={party===1?"selected":""} onClick={()=>setParty(1)}>Just me</button><button type="button" className={party===2?"selected":""} onClick={()=>setParty(2)}>Me + one</button></div></fieldset><fieldset><legend>3 / Booking details</legend><label>Your name<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label><label>Email for confirmation<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" required/></label>{party===2&&<label>Guest’s name<input value={guestName} onChange={e=>setGuestName(e.target.value)} required/></label>}</fieldset><button className="button primary" disabled={loading}>{loading?"Saving…":"Reserve visit"}</button>{message&&<p className="visit-message" role="status">{message}</p>}</form><aside className="visit-summary"><p>YOUR VISIT</p><h2>{reservation?"Confirmed":"Not reserved yet"}</h2><dl><div><dt>When</dt><dd>{selected?formatSlot(slots.find(slot=>slot.id===selected)?.startsAt||""):"Choose a slot"}</dd></div><div><dt>Guests</dt><dd>{party===2?"You + one":"Just you"}</dd></div></dl>{reservation&&<><code>{reservation.id}</code><button className="button" onClick={cancel} disabled={loading}>Cancel reservation</button></>}<small>Capacity, duplicate protection, and cancellations require the Worker API + D1 deployment described in this repo.</small></aside></section></main>;
}
