"use client";
import { useState } from "react";
import { SiteHeader } from "@/components/SiteHeader";
import { useLocalStorage } from "@/lib/storage";
import type { Preferences } from "@/types/event";

type User={name:string;email:string}; type Reservation={id:string;space:string;day:string;time:string;plusOne:boolean}; type Update={id:string;name:string;status:string;note:string;time:string};
const spaces=[{name:"Recharge Lounge",detail:"Wi-Fi · Charging · Coffee · Snacks",availability:"12 spots available"},{name:"Focus Space",detail:"Quiet work · 30 or 60 minutes",availability:"6 desks available"},{name:"Coffee at Product.ai",detail:"Take a break. Meet someone from the community.",availability:"Tables from 1:30 PM"}];
const activity=[{name:"Tess",place:"Product.ai HQ",state:"Now"},{name:"David",place:"Golden Hour",state:"6:00 PM"},{name:"Maya",place:"Future of Spatial Computing",state:"Going"}];
const sampleUpdates:Update[]=[{id:"a",name:"David",status:"Worth it",note:"Good founder crowd. The room is still easy to move through.",time:"4m"},{id:"b",name:"Sara",status:"Long line",note:"Around 20 minutes at the door.",time:"9m"},{id:"c",name:"Alex",status:"Parking issue",note:"Use valet. Street parking is difficult.",time:"12m"}];
const emptyPrefs:Preferences={name:"",city:"la",identity:[],goals:[],interests:[],formats:[],excludedFormats:[],locations:[]};

export default function MissionHQPage(){
  const [prefs]=useLocalStorage<Preferences>("techWeekPreferences",emptyPrefs); const [user,setUser]=useLocalStorage<User|null>("missionHQUser",null); const [reservations,setReservations]=useLocalStorage<Reservation[]>("missionHQReservations",[]); const [updates,setUpdates]=useLocalStorage<Update[]>("alphaUpdates",[]);
  const [name,setName]=useState(prefs.name);const[email,setEmail]=useState("");const[booking,setBooking]=useState<string|null>(null);const[time,setTime]=useState("2:30 PM");const[plusOne,setPlusOne]=useState(false);const[status,setStatus]=useState("Worth it");const[note,setNote]=useState("");
  if(!user)return <main><SiteHeader/><section className="hq-lock wrap"><div className="mission-grid"/><div className="unlock-card"><p className="mono-label">PRODUCT.AI / MISSION HQ</p><h1>Unlock your<br/>Tech Week home base.</h1><p>See where the community is heading, reserve a place to reset, and share useful local context.</p><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="First name"/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="button primary" disabled={!name.trim()||!email.includes("@")} onClick={()=>setUser({name:name.trim(),email:email.trim()})}>Join Mission HQ</button><small>Prototype sign-in. Nothing leaves this browser.</small></div></section></main>;
  const reserve=()=>{if(!booking)return;setReservations([...reservations,{id:crypto.randomUUID(),space:booking,day:"Tuesday",time,plusOne}]);setBooking(null);setPlusOne(false)};
  const post=()=>{if(!note.trim())return;setUpdates([{id:crypto.randomUUID(),name:user.name,status,note:note.trim(),time:"Now"},...updates]);setNote("")};
  return <main><SiteHeader/><section className="hq-head wrap"><div><p className="mono-label">MISSION HQ / {(prefs.city||"la")==="sf"?"SAN FRANCISCO":"LOS ANGELES"}</p><h1>Good afternoon,<br/>{user.name}.</h1><p>Your Tech Week home base.</p></div><button className="sign-out" onClick={()=>setUser(null)}>Sign out</button></section>
    <section className="hq-dashboard wrap"><div className="mission-map"><p>ALPHA ACTIVITY <span>DEMO DATA</span></p><div className="map-field"><i className="map-dot one"/><i className="map-dot two"/><i className="map-dot three"/><div className="hq-marker">◆<span>PRODUCT.AI HQ</span></div>{activity.map((item,i)=><div className={`alpha alpha-${i+1}`} key={item.name}><b>{item.name}</b><span>{item.place} · {item.state}</span></div>)}</div></div>
      <div className="hq-spaces"><p className="panel-title">AT PRODUCT.AI</p>{spaces.map(space=><article key={space.name}><div><h2>{space.name}</h2><p>{space.detail}</p><span>{space.availability}</span></div><button className="button small" onClick={()=>setBooking(space.name)}>Reserve</button></article>)}</div>
    </section>
    {booking&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setBooking(null)}><section className="booking-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><p className="mono-label">RESERVE / TUESDAY</p><h2>{booking}</h2><label>Choose a time<select value={time} onChange={e=>setTime(e.target.value)}>{["2:00 PM","2:30 PM","3:00 PM","3:30 PM"].map(x=><option key={x}>{x}</option>)}</select></label><label className="plus-one"><input type="checkbox" checked={plusOne} onChange={e=>setPlusOne(e.target.checked)}/> Me + 1</label><button className="button primary" onClick={reserve}>Reserve</button><button className="modal-close" onClick={()=>setBooking(null)}>Cancel</button></section></div>}
    <section className="hq-lower wrap"><div><p className="panel-title">YOUR RESERVATIONS</p>{reservations.length?reservations.map(r=><article className="reservation" key={r.id}><strong>{r.space}</strong><span>{r.day} · {r.time}{r.plusOne?" · You + 1":""}</span></article>):<p className="quiet">No reservations yet. Your week still has breathing room.</p>}</div><div><p className="panel-title">ALPHA LIVE <span>LOCAL PROTOTYPE</span></p><div className="update-composer"><div>{["Worth it","Good crowd","Long line","Parking issue","Quiet"].map(x=><button className={status===x?"active":""} onClick={()=>setStatus(x)} key={x}>{x}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What should people know?"/><button className="button primary small" onClick={post}>Post update</button></div><div className="updates">{[...updates,...sampleUpdates].map(u=><article key={u.id}><div><strong>{u.name}</strong><span>{u.time}</span></div><b>{u.status}</b><p>{u.note}</p></article>)}</div></div></section>
  </main>;
}
