"use client";
import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { useLocalStorage } from "@/lib/storage";
import { downloadCalendar } from "@/lib/calendar";
import { eventsByCity } from "@/lib/events";
import type { Preferences } from "@/types/event";

const empty:Preferences={name:"",city:"la",identity:[],goals:[],interests:[],formats:[],excludedFormats:[],locations:[]};
const mins=(value:string)=>{const [h,m]=value.split(":").map(Number);return h*60+m};
const dayName=(date:string,short=false)=>new Date(`${date}T12:00:00`).toLocaleDateString("en-US",short?{weekday:"short"}:{weekday:"long",month:"long",day:"numeric"});

export default function LineupPage(){
  const [prefs]=useLocalStorage<Preferences>("techWeekPreferences",empty); const [ids,setIds]=useLocalStorage<string[]>("techWeekLineup",[]); const [registered,setRegistered]=useLocalStorage<Record<string,boolean>>("techWeekRegistrationStatus",{}); const [pending,setPending]=useLocalStorage<Record<string,boolean>>("techWeekRegistrationPending",{});
  const city=prefs.city||"la"; const cityName=city==="sf"?"San Francisco":"Los Angeles"; const cityShort=city.toUpperCase(); const cityEvents=eventsByCity[city];
  const selected=cityEvents.filter(event=>ids.includes(event.id)).sort((a,b)=>a.date.localeCompare(b.date)||a.startTime.localeCompare(b.startTime));
  const days=[...new Set(selected.map(e=>e.date))];
  const warnings=selected.flatMap((event,index)=>{const next=selected[index+1];if(!next||next.date!==event.date)return[];const gap=mins(next.startTime)-mins(event.startTime);const list:string[]=[];if(gap<90)list.push(`Potential schedule conflict: ${event.name} and ${next.name} start ${gap} minutes apart.`);else if(event.neighborhood!==next.neighborhood&&gap<150)list.push(`${event.neighborhood} → ${next.neighborhood}: leave real travel time between these events.`);return list;});
  function savePoster(){const canvas=document.createElement("canvas");canvas.width=1200;canvas.height=1500;const c=canvas.getContext("2d")!;c.fillStyle="#f3ff53";c.fillRect(0,0,1200,1500);c.fillStyle="#111111";c.fillRect(48,48,1104,1404);c.fillStyle="#f3ff53";c.font="700 24px monospace";c.fillText(`PRODUCT.AI × ${cityShort} TECH WEEK`,82,94);c.fillStyle="#ffffff";c.font="800 86px Arial";c.fillText(`${(prefs.name||"MY").toUpperCase()}’S`,78,205);c.fillText("WEEKBOARD",78,292);c.fillStyle="#f3ff53";c.font="22px monospace";c.fillText(`${cityName.toUpperCase()} / ${selected.length} ROOMS / ZERO FOMO`,82,342);let y=420;for(const day of days){c.fillStyle="#f3ff53";c.font="700 22px monospace";c.fillText(dayName(day).toUpperCase(),82,y);y+=45;for(const event of selected.filter(e=>e.date===day).slice(0,5)){c.fillStyle="#ffffff";c.font="700 30px Arial";c.fillText(event.name.slice(0,56),82,y);c.fillStyle="#a1a1aa";c.font="18px monospace";c.fillText(`${event.startTimeDisplay}  ·  ${event.neighborhood}`.toUpperCase(),82,y+27);y+=76;}y+=24;if(y>1380)break;}const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download=`${city}-tech-week-weekboard.png`;a.click();}
  return <main><SiteHeader/><section className="lineup-head wrap"><p className="mono-label">MY WEEK / {selected.length} EVENTS / {cityShort}</p><div><h1>{(prefs.name||"My")}’s<br/>Weekboard.</h1><div className="lineup-actions"><button className="button" disabled={!selected.length} onClick={()=>downloadCalendar(selected)}>Add to calendar</button><button className="button primary" disabled={!selected.length} onClick={savePoster}>Save poster</button></div></div></section>
    {!selected.length?<section className="empty-week wrap"><h2>Your week is still open.</h2><p>Choose the rooms that earn a place on your board.</p><Link className="button primary" href="/events">See my matches</Link></section>:<>
      {warnings.length>0&&<section className="warning-stack wrap">{warnings.map(w=><p key={w}><span>PLAN NOTE</span>{w}</p>)}</section>}
      <section className="week-os wrap"><div className="os-titlebar"><span><i/><i/><i/></span><b>product.ai / weekboard.app</b><em>PERSONAL MODE</em></div><div className="os-layout"><aside className="os-rail"><div><span>CITY</span><strong>{cityShort}</strong></div><div><span>ROOMS</span><strong>{String(selected.length).padStart(2,"0")}</strong></div><div><span>DAYS</span><strong>{String(days.length).padStart(2,"0")}</strong></div><div><span>CONFLICTS</span><strong>{String(warnings.length).padStart(2,"0")}</strong></div><p>Curated from {cityEvents.length.toLocaleString()} official listings.</p></aside><div className="festival-board"><header><div><span>PRODUCT.AI × TECH WEEK</span><h2>{cityName}<br/>Weekboard</h2></div><p>{city==="sf"?"OCT 05—11":"OCT 12—18"}<br/>2026</p></header><div className="poster-days">{days.map(day=><section className="poster-day" key={day}><div className="poster-day-label"><b>{dayName(day,true).toUpperCase()}</b><span>{day.slice(-2)}</span></div><div className="poster-event-stack">{selected.filter(e=>e.date===day).map((event,index)=><article className={index===0?"headliner":""} key={event.id}><div><h3>{event.name}</h3><p>{event.startTimeDisplay} · {event.neighborhood} · {event.hostDisplay}</p>{pending[event.id]&&!registered[event.id]&&<div className="registration-check"><span>RSVP done?</span><button onClick={()=>setRegistered({...registered,[event.id]:true})}>Yes</button><button onClick={()=>setPending({...pending,[event.id]:false})}>Later</button></div>}{registered[event.id]&&<strong className="registered">RSVP LOCKED ✓</strong>}</div><button className="remove-event" onClick={()=>setIds(ids.filter(id=>id!==event.id))} aria-label={`Remove ${event.name}`}>×</button></article>)}</div></section>)}</div><footer><span>BUILD LESS FOMO.</span><span>{(prefs.name||"MY").toUpperCase()}’S TECH WEEK / {cityShort}</span></footer></div></div></section>
      <section className="hq-invite wrap"><p>YOUR WEEK IS PLANNED.</p><div><h2>Now find your home base.</h2><p>Recharge. Work. Meet people. Head back out.</p><Link className="button primary" href="/mission-hq">Enter Mission HQ →</Link></div></section>
    </>}
  </main>;
}
